config/routes.rb
Rails.application.routes.draw do
  resources :energy_usages
  resources :productions
  resources :users
  resources :reserves
  resources :live_data
  resources :energy_usages
  
 root 'static_pages#home'
  get '/contact', to: 'static_pages#contact'
  get '/about', to: 'static_pages#about'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'productions/show', to: 'productions#show'
  post 'productions/show', to: 'productions#show'
  get 'energy_usages', to: 'energy_usages#index'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  
  
  end

app/models/energy_usage.rb
class EnergyUsage < ApplicationRecord
end

app/controllers/energy_usages_controller.rb
class EnergyUsagesController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy
  
  # Displays results of matches played thus far
  def index
    if !logged_in?
      flash[:warning] = "Please log in to access results."
      redirect_to energy_usage_path
    else
       @energy_usages = EnergyUsage.all
    end
  end

 

  # GET /energy_usages/1
  # GET /energy_usages/1.json
  def show
  end

  # GET /energy_usages/new
  def new
    @energy_usage = EnergyUsage.new
  end

  # GET /energy_usages/1/edit
  def edit
  end

  # POST /energy_usages
  # POST /energy_usages.json
  def create
    @energy_usage = EnergyUsage.new(energy_usage_params)

    respond_to do |format|
      if @energy_usage.save
        format.html { redirect_to @energy_usage, notice: 'Energy usage was successfully created.' }
        format.json { render :show, status: :created, location: @energy_usage }
      else
        format.html { render :new }
        format.json { render json: @energy_usage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /energy_usages/1
  # PATCH/PUT /energy_usages/1.json
  def update
    respond_to do |format|
      if @energy_usage.update(energy_usage_params)
        format.html { redirect_to @energy_usage, notice: 'Energy usage was successfully updated.' }
        format.json { render :show, status: :ok, location: @energy_usage }
      else
        format.html { render :edit }
        format.json { render json: @energy_usage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /energy_usages/1
  # DELETE /energy_usages/1.json
  def destroy
    @energy_usage.destroy
    respond_to do |format|
      format.html { redirect_to energy_usages_url, notice: 'Energy usage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_energy_usage
      @energy_usage = EnergyUsage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def energy_usage_params
      params.require(:energy_usage).permit(:country, :energy_use, :gdp_per_capita)
    end
end

app/helpers/energy_usages_helper.rb
module EnergyUsagesHelper

	def energy
 
 	@test = EnergyUsage.select('country, energy_use, gdp_per_capita, population').where.not(energy_use: nil, gdp_per_capita: nil, population: nil, country: "Qatar").map{|f| [f.energy_use, f.gdp_per_capita, f.population, f.country]}

	#@x_axis = EnergyUsage.select('energy_use')

  	end

end

app/views/energy_usages/_form.html.erb
<%= form_with(model: energy_usage, local: true) do |form| %>
  <% if energy_usage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(energy_usage.errors.count, "error") %> prohibited this energy_usage from being saved:</h2>

      <ul>
      <% energy_usage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country, id: :energy_usage_country %>
  </div>

  <div class="field">
    <%= form.label :energy_use %>
    <%= form.number_field :energy_use, id: :energy_usage_energy_use %>
  </div>

  <div class="field">
    <%= form.label :gdp_per_capita %>
    <%= form.number_field :gdp_per_capita, id: :energy_usage_gdp_per_capita %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/energy_usages/edit.html.erb
<h1>Editing Energy Usage</h1>

<%= render 'form', energy_usage: @energy_usage %>

<%= link_to 'Show', @energy_usage %> |
<%= link_to 'Back', energy_usages_path %>

app/views/energy_usages/index.html.erb
<h1>Energy Usages</h1>

<div id="container" style="height: 700px; min-width: 350px; max-width: 800px; margin: 0 auto"></div>

<html>
  <head>

    <p> The link between energy consumption and economic growth has been a topic of wide discussion. A large number of studies have attempted to derive the causal relationship between energy consumption and economic growth, however no clear consensus has emerged.13 This can be partly attributed to the fact that the link between energy and prosperity is not always unidirectional. Gaining access to electricity and other energy sources may provide an initial increase in GDP, but having higher GDP may in turn drive higher energy consumption. Additionally, progress in development outcomes can be complex: a number of parameters may be improving at the same time. If, for example, energy access and consumption, nutrition, education, health, and sanitation are all improving simultaneously (and having complex relationships with one another), it can be hard to directly attribute improvement in living standards back to a single parameter. </p>

<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/highcharts-more.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>

   <script type="text/javascript">

   Highcharts.chart('container', {

    chart: {
        type: 'bubble',
        plotBorderWidth: 1,
        zoomType: 'xy'
    },

    legend: {
        enabled: false
    },

    title: {
        text: 'Energy usage per capita vs GDP per capita, 2014'
    },

    subtitle: {
        text: 'Source: <a href="https://ourworldindata.org/">Our world in Data</a>'
    },

    xAxis: {
        startOnTick: false,
        endOnTick: false,
        title: {
            text: 'GDP per capita (2011 int-$)'
        },
        labels: {
            format: '{value} $'
        },
        maxPadding: 0.2,
        plotLines: [{
            color: 'black',
            dashStyle: 'dot',
            width: 2,
            value: 7,
            zIndex: 3
        }]
    },


    yAxis: {
        gridLineWidth: 1,
        title: {
            text: 'Energy use per capita (kg oil equivalent)'
        },
        labels: {
            format: '{value} kWh'
        },
        plotLines: [{
            color: 'black',
            dashStyle: 'dot',
            width: 2,
            value: 5,
            zIndex: 3
        }]
    },

    tooltip: {
        useHTML: true,
        headerFormat: '<table>',
        pointFormat: '<tr><th colspan="2"><h3>{point.name}</h3></th></tr>' +
            '<tr><th>Energy usage:</th><td>{point.x}</td></tr>' +
            '<tr><th>GDP per capita:</th><td>{point.y}$</td></tr>' +
            '<tr><th>Population:</th><td>{point.z}</td></tr>',
        footerFormat: '</table>',
        followPointer: true
    },

    plotOptions: {
        series: {
            dataLabels: {
                enabled: false,
                format: '{point.name}'
            }
        }
    },

    series: [{
        data: (<%=raw energy %>)
    }]

});

    </script>
  </head>
  
 
</html>

app/views/energy_usages/new.html.erb
<h1>New Energy Usage</h1>

<%= render 'form', energy_usage: @energy_usage %>

<%= link_to 'Back', energy_usages_path %>

app/views/energy_usages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Country:</strong>
  <%= @energy_usage.country %>
</p>

<p>
  <strong>Energy use:</strong>
  <%= @energy_usage.energy_use %>
</p>

<p>
  <strong>Gdp per capita:</strong>
  <%= @energy_usage.gdp_per_capita %>
</p>

<%= link_to 'Edit', edit_energy_usage_path(@energy_usage) %> |
<%= link_to 'Back', energy_usages_path %>