config/routes.rb
Rails.application.routes.draw do
  resources :energy_usages
  resources :productions
  resources :users
  resources :reserves
  resources :live_data
  resources :energy_usages
  
 root 'static_pages#home'
  get '/contact', to: 'static_pages#contact'
  get '/about', to: 'static_pages#about'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'productions/show', to: 'productions#show'
  post 'productions/show', to: 'productions#show'
  get 'energy_usages', to: 'energy_usages#index'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  
  
  end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small style="color: grey;">
    The Oil statistics APP is created by Kanat Kussembayev
  </small>
  <nav>
    <ul >
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="https://www.oilandgaspeople.com/news/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar-fixed-top navbar-inverse"> 
  <div class="container">
    <nav>
       <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>  
                               
      </button>
      <a class="navbar-brand" href="/">Oil Statistics App</a>
    </div>
      <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Oil Reserves", reserves_path %></li>
        <li><%= link_to "Oil Production", productions_path %></li>
        <li><%= link_to "Oil Production Live Data", live_data_path %></li>
        <li><%= link_to "Energy usage analysis", energy_usages_path %></li>
        <% if logged_in? %>
          <% if current_user.admin == true %>
            <li><%= link_to "Users", users_path %></li>
          <% end %>
          <li class="dropdown">
            <a href="current_user" class="dropdown-toggle" data-toggle="dropdown">
              <%= "Welcome, #{current_user.name}" %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "Log out", logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <li><%= link_to "Sign up", signup_path, class: "btn btn-lg btn-primary btn-xs" %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_link_tag    'application', media: 'all' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta charset="utf-8">
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
    
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag 'http://yandex.st/bootstrap/3.1.1/css/bootstrap.min.css' %>
  <%= javascript_include_tag 'http://yandex.st/bootstrap/3.1.1/js/bootstrap.min.js' %>
  

  <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug (params) if Rails.env.development? %>
    </div>
  </body>
</html>